// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package users

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

// User defines model for User.
type User struct {
	Completed    bool       `json:"completed"`
	CompletedAt  *time.Time `json:"completed_at,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Email        string     `json:"email"`
	Id           int32      `json:"id"`
	Name         string     `json:"name"`
	PasswordHash string     `json:"password_hash"`
	Username     string     `json:"username"`
}

// UsersUserIdBody defines model for users_userId_body.
type UsersUserIdBody struct {
	Completed *bool   `json:"completed,omitempty"`
	Task      *string `json:"task,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody = NewUser

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserJSONBody
