// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package users

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	JWTAuthScopes = "JWTAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Comment      *string `json:"comment,omitempty"`
	Email        string  `json:"email"`
	Enterprise   *string `json:"enterprise,omitempty"`
	ExternalId   *string `json:"external_id,omitempty"`
	IsAdmin      bool    `json:"is_admin"`
	Name         string  `json:"name"`
	PasswordHash string  `json:"password_hash"`
	Phone        *string `json:"phone,omitempty"`
	Username     string  `json:"username"`
}

// User defines model for User.
type User struct {
	BadPasswordCount     int32               `json:"bad_password_count"`
	Comment              *string             `json:"comment,omitempty"`
	CreateTime           time.Time           `json:"create_time"`
	Creator              int32               `json:"creator"`
	Email                openapi_types.Email `json:"email"`
	Enterprise           *string             `json:"enterprise,omitempty"`
	ExternalId           *string             `json:"external_id,omitempty"`
	Id                   int32               `json:"id"`
	InactivationReason   *string             `json:"inactivation_reason,omitempty"`
	InactivationTime     *time.Time          `json:"inactivation_time,omitempty"`
	IsActive             bool                `json:"is_active"`
	IsAdmin              bool                `json:"is_admin"`
	IsLocked             bool                `json:"is_locked"`
	LastModificationTime *time.Time          `json:"last_modification_time,omitempty"`
	LastModificationUser *int32              `json:"last_modification_user,omitempty"`
	Name                 string              `json:"name"`
	PasswordHash         string              `json:"password_hash"`
	Phone                *string             `json:"phone,omitempty"`
	Username             string              `json:"username"`
}

// UserList defines model for UserList.
type UserList struct {
	CreateTime time.Time           `json:"create_time"`
	Creator    int32               `json:"creator"`
	Email      openapi_types.Email `json:"email"`
	Id         int32               `json:"id"`
	IsAdmin    bool                `json:"is_admin"`
	IsLocked   bool                `json:"is_locked"`
	Name       string              `json:"name"`
	Username   string              `json:"username"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

// UsersListParams defines parameters for UsersList.
type UsersListParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// UsersCreateJSONBody defines parameters for UsersCreate.
type UsersCreateJSONBody = NewUser

// UsersCreateJSONRequestBody defines body for UsersCreate for application/json ContentType.
type UsersCreateJSONRequestBody = UsersCreateJSONBody
