// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package users

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	JWTAuthScopes = "JWTAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// JsonWebToken defines model for JsonWebToken.
type JsonWebToken struct {
	Token string `json:"token"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Comment      *string `json:"comment,omitempty"`
	Email        string  `json:"email"`
	Enterprise   *string `json:"enterprise,omitempty"`
	ExternalId   *string `json:"external_id,omitempty"`
	IsAdmin      *bool   `json:"is_admin,omitempty"`
	Name         string  `json:"name"`
	PasswordHash string  `json:"password_hash"`
	Phone        *string `json:"phone,omitempty"`
	Username     string  `json:"username"`
}

// User defines model for User.
type User struct {
	BadPasswordCount     *int32              `json:"bad_password_count,omitempty"`
	Comment              *string             `json:"comment,omitempty"`
	CreateTime           *time.Time          `json:"create_time,omitempty"`
	Creator              int32               `json:"creator"`
	Email                openapi_types.Email `json:"email"`
	Enterprise           *string             `json:"enterprise,omitempty"`
	ExternalId           *string             `json:"external_id,omitempty"`
	Id                   int32               `json:"id"`
	InactivationReason   *string             `json:"inactivation_reason,omitempty"`
	InactivationTime     *time.Time          `json:"inactivation_time,omitempty"`
	IsActive             *bool               `json:"is_active,omitempty"`
	IsAdmin              *bool               `json:"is_admin,omitempty"`
	IsLocked             *bool               `json:"is_locked,omitempty"`
	LastModificationTime *time.Time          `json:"last_modification_time,omitempty"`
	LastModificationUser *int32              `json:"last_modification_user,omitempty"`
	Name                 string              `json:"name"`
	PasswordHash         string              `json:"password_hash"`
	Phone                *string             `json:"phone,omitempty"`
	Username             string              `json:"username"`
}

// UserList defines model for UserList.
type UserList struct {
	CreateTime *time.Time          `json:"create_time,omitempty"`
	Creator    int32               `json:"creator"`
	Email      openapi_types.Email `json:"email"`
	Id         int32               `json:"id"`
	IsAdmin    *bool               `json:"is_admin,omitempty"`
	IsLocked   *bool               `json:"is_locked,omitempty"`
	Name       string              `json:"name"`
	Username   string              `json:"username"`
}

// UserLogin defines model for UserLogin.
type UserLogin struct {
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody = NewUser

// LoginUserJSONBody defines parameters for LoginUser.
type LoginUserJSONBody = UserLogin

// SendResetPasswordJSONBody defines parameters for SendResetPassword.
type SendResetPasswordJSONBody = string

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserJSONBody

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginUserJSONBody

// SendResetPasswordJSONRequestBody defines body for SendResetPassword for application/json ContentType.
type SendResetPasswordJSONRequestBody = SendResetPasswordJSONBody
