// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package users

import (
	"fmt"
	"net/http"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// UsersList returns a list of users
	// (GET /users)
	UsersList(ctx echo.Context, params UsersListParams) error
	// UsersCreate will create a new user
	// (POST /users)
	UsersCreate(ctx echo.Context) error
	// UsersDelete allows to delete a specific userId
	// (DELETE /users/{userId})
	UsersDelete(ctx echo.Context, userId int32) error
	// UsersGet will retrieve in backend all information about a specific userId
	// (GET /users/{userId})
	UsersGet(ctx echo.Context, userId int32) error
	// UsersUpdate allows to modify information about a specific userId
	// (PUT /users/{userId})
	UsersUpdate(ctx echo.Context, userId int32) error
	// UsersChangePassword allows a user to change it's own password
	// (PUT /users/{userId}/changepassword)
	UsersChangePassword(ctx echo.Context, userId int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// UsersList converts echo context to params.
func (w *ServerInterfaceWrapper) UsersList(ctx echo.Context) error {
	var err error

	ctx.Set(JWTAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UsersListParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UsersList(ctx, params)
	return err
}

// UsersCreate converts echo context to params.
func (w *ServerInterfaceWrapper) UsersCreate(ctx echo.Context) error {
	var err error

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UsersCreate(ctx)
	return err
}

// UsersDelete converts echo context to params.
func (w *ServerInterfaceWrapper) UsersDelete(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UsersDelete(ctx, userId)
	return err
}

// UsersGet converts echo context to params.
func (w *ServerInterfaceWrapper) UsersGet(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UsersGet(ctx, userId)
	return err
}

// UsersUpdate converts echo context to params.
func (w *ServerInterfaceWrapper) UsersUpdate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UsersUpdate(ctx, userId)
	return err
}

// UsersChangePassword converts echo context to params.
func (w *ServerInterfaceWrapper) UsersChangePassword(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(JWTAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UsersChangePassword(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/users", wrapper.UsersList)
	router.POST(baseURL+"/users", wrapper.UsersCreate)
	router.DELETE(baseURL+"/users/:userId", wrapper.UsersDelete)
	router.GET(baseURL+"/users/:userId", wrapper.UsersGet)
	router.PUT(baseURL+"/users/:userId", wrapper.UsersUpdate)
	router.PUT(baseURL+"/users/:userId/changepassword", wrapper.UsersChangePassword)

}
